### PR TITLE
Disable irrelevant pylint disable instructions

### LINKED ISSUE #214: DOC: irrelevant pylint disable
https://github.com/Segelzwerg/Rechnung/blob/da337c9d3dcfc9ed4adf22932f92924a3355a566/invoice/pdf_generator.py#L15C5-L15C87

@iTitus  do we still need it? I believe it is not working anyway.

### PR DESCRIPTION
**Pull request by iTitus**
Closes #214

### CODE REVIEW

**Review by Segelzwerg — COMMENTED** [review]
Shouldn't the disable above the function?

**Comment by iTitus** [comment]
> Shouldn't the disable above the function? 

I don't understand?

**Comment by Segelzwerg** [comment]
> > Shouldn't the disable above the function?
> 
> I don't understand?

```
# pylint: disable=too-many-locals
def gen_invoice_pdf(invoice, filename_or_io):
...
```
Should it be like this?

**Comment by iTitus** [comment]
Why? With the annotation it works and without the linting fails

**Comment by Segelzwerg** [comment]
> Why? With the annotation it works and without the linting fails

I was under the impression the disable must be above the scope, but apparently pylint recommends to put it into the scope.
https://pylint.readthedocs.io/en/stable/user_guide/messages/message_control.html

**Review by Segelzwerg — APPROVED** [review]

**Pull request merged**
